# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 01:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=28, verbose_name='fullname')),
                ('privilege', models.SmallIntegerField(choices=[(0, 'User'), (14, 'Administrator')], default=0, verbose_name='privilege')),
                ('password', models.CharField(blank=True, max_length=8, null=True, verbose_name='password')),
                ('group_id', models.CharField(blank=True, max_length=7, null=True, verbose_name='group id')),
            ],
            options={
                'abstract': False,
                'db_table': 'zk_user',
                'swappable': 'ZK_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='user id')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('status', models.IntegerField(verbose_name='status')),
            ],
            options={
                'db_table': 'zk_attendance',
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('serialnumber', models.CharField(max_length=100, unique=True, verbose_name='serialnumber')),
                ('ip', models.CharField(max_length=15, unique=True, verbose_name='ip')),
                ('port', models.IntegerField(default=4370, verbose_name='port')),
            ],
            options={
                'db_table': 'zk_terminal',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='zkcluster.Terminal'),
        ),
        migrations.AddField(
            model_name='user',
            name='terminals',
            field=models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='zkcluster.Terminal', verbose_name='terminals'),
        ),
    ]
