# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zkcluster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='port',
            field=models.IntegerField(default=4370),
        ),
    ]
